---
config:
  layout: elk
  theme: redux
  look: neo
---
stateDiagram
  direction BT
  [*] --> boot
  boot --> net_off:System configured / Network "Task" created
  net_off --> mqtt_off:Connects to Wi-Fi network
  mqtt_off --> net_off:Wi-Fi disconnected
  mqtt_off --> fetching:Connects to "Broker"
  fetching --> working:Update MQTT context / IDLE = FALSE
  working --> fetching:Needs to update context
  working --> waiting:Makes HTTP request
  waiting --> working:REST response/TIMEOUT / From WORKING
  sleep --> boot:Sleeping / User detected
  boot --> configuring:GPIO4 high level
  configuring --> boot:BLE EXIT command or TIMEOUT
  working --> mqtt_off:"Broker" disconnected
  waiting --> mqtt_off:"Broker" disconnected
  working --> net_off:Wi-Fi disconnected
  waiting --> net_off:Wi-Fi disconnected
  ics --> sleep:No user detected / PIR Sensor
  net_off:net off
  mqtt_off:mqtt off
  ics:idle-capable states